package crud

import (
	"database/sql"

	"time"

	_ "github.com/lib/pq"
)

func Connect(connectionString string) (*sql.DB, error) {
	db, err := sql.Open("postgres", connectionString)
	if err != nil {
		return nil, err
	}
	err = db.Ping()
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(2)
	db.SetMaxIdleConns(5)
	return db, nil
}

type dual struct {
	ID int `json:"id"`
}

var Dual1 = dual{ID: 1}

type Category struct {
	ID          int    `json:"id"`
	Nama        string `json:"nama"`
	Description string `json:"description"`
}

var Category1 = []Category{
	{ID: 1, Nama: " ", Description: " "},
}

type Product struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
	Price int    `json:"price"`
	Stock int    `json:"stock"`
	// CategoryID int      `json:"category_id"`
	// Category   Category `json:"category"`
}

type CheckoutItem1 struct {
	ProductID int `json:"product_id"`
	Quantity  int `json:"quantity"`
}

type CheckoutRequest struct {
	Items []CheckoutItem1 `json:"items"`
}

// {
//     "items": [
//         {
//             "product_id": 1,
//             "quantity": 2
//         },
//         {
//             "product_id": 2,
//             "quantity": 3
//         }
//     ]
// }

type TransactionDetail struct {
	ID            int    `json:"id"`
	TransactionID int    `json:"transaction_id"`
	ProductID     int    `json:"product_id"`
	ProductName   string `json:"product_name,omitempty"`
	Quantity      int    `json:"quantity"`
	Subtotal      int    `json:"subtotal"`
}

// create table public.transaction_details (
//   id bigint generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   transaction_id bigint null,
//   product_id bigint null,
//   quantity bigint not null,
//   subtotal bigint not null,
//   constraint transaction_details_pkey primary key (id),
//   constraint transaction_details_product_id_fkey foreign KEY (product_id) references "Product" (id),
//   constraint transaction_details_transaction_id_fkey foreign KEY (transaction_id) references transactions (id) on delete CASCADE
// ) TABLESPACE pg_default;

type Transaction struct {
	ID          int                 `json:"id"`
	TotalAmount int                 `json:"total_amount"`
	CreatedAt   time.Time           `json:"created_at"`
	Details     []TransactionDetail `json:"details"`
}

// create table public.transactions (
//   id bigint generated by default as identity not null,
//   total_amount bigint not null,
//   created_at timestamp without time zone null default CURRENT_TIMESTAMP,
//   constraint transactions_pkey primary key (id)
// ) TABLESPACE pg_default;

type BestProduct struct {
	Nama       string `json:"nama"`
	QtyTerjual int    `json:"qty_terjual"`
}

type TodayReportResponse struct {
	TotalRevenue   int         `json:"total_revenue"`
	TotalTransaksi int         `json:"total_transaksi"`
	ProdukTerlaris BestProduct `json:"produk_terlaris"`
}

type ReportResponse struct {
	TotalRevenue   int         `json:"total_revenue"`
	TotalTransaksi int         `json:"total_transaksi"`
	ProdukTerlaris BestProduct `json:"produk_terlaris"`
}
